apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::536864977932:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::536864977932:role/eksctl-simple-jwt-api-2-nodegroup-NodeInstanceRole-CSYEOIGWL59K
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-15T02:10:35Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1669"
  uid: 83c37bad-1148-4dda-81da-4c3cc78d9c3c
